{{ define "libchart.ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "libchart.fullname" . }}-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.domain | default "localhost" }}
  rules:
  - host: {{ .Values.ingress.domain | default "localhost"}}
    http:
      paths:
      - path: {{ .Values.ingress.path | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "libchart.fullname" . }}-svc
            port:
              number: {{ .Values.ingress.port | default 443 }}      
{{- end }}